### PR TITLE
Media upload is a first class citizen

### PR DESCRIPTION
**Pull request by hmcfletch**
I need to be able to upload media ahead of time, so I pulled the media uploading out into its own module.

I also refactored some of the tests around updating with media, since the actual upload testing is done in its own spec now.

### CODE REVIEW

**Comment by hmcfletch** [comment]
The failing tests were not part of this PR. Something in the `null_object_spec `.

**Comment by sferik** [comment]
What’s your use case for needing to upload media ahead of time?

**Comment by hmcfletch** [comment]
We upload video ahead of time so that the tweet goes out without a delay. Not a huge deal, but it's how we use the API.

**Comment by hmcfletch** [comment]
looks like there are a few other PR's that might better handle this. Going to close.

**Pull request closed without merging**
