### PR TITLE
Add support for premium search

### PR DESCRIPTION
**Pull request by ryanwi**
**Recent Announcement**
* https://blog.twitter.com/developer/en_us/topics/tools/2017/introducing-twitter-premium-apis.html
* https://developer.twitter.com/en/docs/tweets/search/overview/premium
* https://developer.twitter.com/en/docs/tweets/search/guides/integrating-premium

### Description
This PR is a first attempt at adding support for Twitter's new premium search api. There are some significant differences between the premium search's request and response and the standard/ REST endpoints, which is why a separate module is introduced into the gem.

Significant differences include:
* URLs are different and dynamic. Every app's development environment is now part of the URL.
* Requests can be made with GET or POST
* POST requests require a serialized JSON body
* Response payloads are different. 
* Paging is different

### CODE REVIEW

**Comment by sferik** [comment]
@ryanwi Can you please rebase to resolve conflicts?

**Comment by ryanwi** [comment]
@sferik rebased. Is this something that can be used for premium search? Or is there another plan? I know there are build failures and may take some time until I can get back to addressing those.

**Comment by dekaikiwi** [comment]
@ryanwi Are there plans to add support for the Account Activity API, webhook/user subscription APIs here too?

https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/overview

**Comment by ran5000** [comment]
any update when this PR is going to be merged? would love to see it as part of the master branch :)

**Pull request closed without merging**
