### PR TITLE
Take a copy of any options hash if we're modifying it.

### PR DESCRIPTION
**Pull request by rob-murray**
Dont know if this is by design or not but some calls to the gem modify the `options` instance passed in - this can give the caller a surprise if they're not expecting it so it's good to take a copy if we're going to do anything to it.

If you intend to modify the options in the way the code does then just close this PR!

great gem though :thumbsup:

### CODE REVIEW

**Comment by rob-murray** [comment]
If you want I can go over the rest of the gem and do the same, I just had a bug from the `oembed` method so just done that class for now.

**Comment by sferik** [comment]
Yeah, ideally this would be done consistently, throughout the codebase.

There should also be tests to ensure this doesn’t get rolled back.

**Comment by rob-murray** [comment]
Sorry for the delay - I've been through the rest of the gem and updated the obvious case where `options` is a Hash and being modified. I've just looked at the methods that are part of the public API as opposed to some internals where I dont have enough context knowledge to determine if I should change them. Apologies if I have missed some cases too. :disappointed:

I'm happy to add specs if necessary but not sure they're totally necessary? I probably wouldn't and eg. I dont think Rails, which also does a lot of `options.dup`, tests this specifically.

**Comment by sferik** [comment]
I just [applied](https://github.com/sferik/twitter/commit/347c5001677041f0412770862592a680ae3135c9) your patch to `master`. Thanks!

**Pull request closed without merging**
