### PR TITLE
Support closing stream

### PR DESCRIPTION
**Pull request by okkez**
In this version, we can close stream as following:

```ruby
client = Twitter::Streaming::Client.new do |config|
  # Set up configuration
end

t = Thread.new do
  client.filter(track: keyword) do |object|
    # process object
  end
end

Signal.trap(:TERM) do
  # terminate process silently
  client.close
  exit true
end
```

### CODE REVIEW

**Comment by sferik** [comment]
@okkez This looks good but it’s causing the tests to fail because it reduces our code coverage percentage. Can you please add some tests that cover this code to ensure there are no regressions in the future. Thanks!

**Comment by okkez** [comment]
Any progress?

**Comment by okkez** [comment]
I've pushed changes for rubocop report.
But still failure caused by latest rubocop breaking changes.

@sferik Could you check this PR again?

**Comment by okkez** [comment]
Thank you for merging!!

**Pull request merged**
