### PR TITLE
Support tweet_mode=extended

### PR DESCRIPTION
**Pull request by fauxparse**
I noticed that a bunch of my tweets were coming back truncated. I've tweaked the `Tweet` class slightly so that I can use `tweet_mode=extended` when requesting a timeline etc to return the full Tweets.

More information here: https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

### CODE REVIEW

**Comment by stve** [comment]
Hi @fauxparse, thanks for the pull request 🎉 

I'm a bit mixed on this as it makes it more difficult to access the raw `text` attribute. I'd be more in favor of letting `text and `full_text` be accessible via `attr_reader` and renaming the method you added to something that doesn't collide with either of those two.

How does that sound?

**Comment by knu** [comment]
I think you should also fix the `full_text` method, which does not take the full_text attribute into account and currently stands in the way of accessing it.

**Comment by christianstanfield** [comment]
I pushed a PR for consideration that retains the full_text attr and updates the existing method to work with extended mode: https://github.com/sferik/twitter/pull/864

**Comment by maia** [comment]
@christianstanfield As I am eagerly hoping for support of `tweet_mode=extended`, is there any news regarding the planned PR? Thanks!

**Comment by chriso0710** [comment]
Agreeing with @knu, @christianstanfield and @maia here. IMHO it would be a very important fix to support the extended mode and the correct full_text/relevant_text. I would like to see a PR to be included in this library.

Just for reference: Below is the way I am handling this issue ATM. Seems to be working. I am using both Streaming (with Tweetstream) and REST APIs.

```ruby
status = @client.status(1234567890, tweet_mode: "extended")

if status.truncated? && status.attrs[:extended_tweet]
            # Streaming API
            t = status.attrs[:extended_tweet][:full_text]
else
            # REST API with tweet_mode=extended, or untruncated text in Streaming API
            t = status.attrs[:text] || status.attrs[:full_text]
end
```

**Pull request closed without merging**
