### PR TITLE
Bump http dependency to 5.0.2

### PR DESCRIPTION
**Pull request by marcbest**
Bumps the `http` dependency to 5.0.2. This fixes a couple of issues:

https://github.com/sferik/t/issues/452

### CODE REVIEW

**Review by pboling — COMMENTED** [review]
Looks like the CI build isn't hooked up to pull requests, so not sure of viability  here... But I'm hoping it works.  Did you test it out @marcbest ?

**Comment by marcbest** [comment]
@pboling seemed to work fine for the project that required the bump. Apart from that haven't had too much time to test

**Comment by cooljeanius** [comment]
Could it go to 5.0.2 actually? So that way it could include [httprb/http@2df5e46](https://github.com/httprb/http/commit/2df5e461bf22d1eba2db72b524630cd99cc2eb4d) and thus (possibly?) address sferik/t#452

**Comment by cooljeanius** [comment]
> Could it go to 5.0.2 actually? So that way it could include [httprb/http@2df5e46](https://github.com/httprb/http/commit/2df5e461bf22d1eba2db72b524630cd99cc2eb4d) and thus (possibly?) address [sferik/t#452](https://github.com/sferik/t/issues/452)

OK I opened marcbest/twitter#1 against this PR to do so

**Comment by marcbest** [comment]
Thanks @cooljeanius 

@sferik is there anything else we need to do to get this in? 🙇 thank you

**Pull request merged**
