### PR TITLE
Added support to new Direct Messages Events endpoint (rebased)

### PR DESCRIPTION
**Pull request by FabienChaynes**
@danicuki: Thanks for your work on this! As @sferik asked on #847 I rebased master and resolved the conflict, I hope you don't mind.

It'd be awesome to have this merged alongside #900 to be able to fully use the [new DM API](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/guides/direct-message-migration) which will replace the one currently used by the gem.

If any work is needed, I'd be glad to help :slightly_smiling_face:

### CODE REVIEW

**Comment by danicuki** [comment]
Awesome @FabienChaynes!!! Thanks

**Comment by abhishek1203** [comment]
@danicuki @FabienChaynes, I need these changes to be incorporated in current project. Thanks for making these changes. Do you guys have any idea when these changes were going to be merged in master (or) Do we have any specific person to whom,I should request to merge these changes.

**Comment by FabienChaynes** [comment]
@abhishek1203 all the conversation about this is present in this PR and in #847, so no we don't have more information :confused:

**Comment by sferik** [comment]
Thanks! I’ll push out a new release shortly.

**Pull request merged**
