### PR TITLE
handle json post requests

### LINKED ISSUE #862: How to make JSON POST for new DM endpoints?
Last week I was playing around with the new DM endpoints and found that I can successfully do this:

`client.send("perform_get", "/1.1/direct_messages/welcome_messages/list.json")`

to make a GET request to fetch current welcome messages. JustWorks. However, the POST endpoints (such as https://dev.twitter.com/rest/reference/post/direct_messages/welcome_messages/new) state the following: 

> Requires a JSON POST body and Content-Type header to be set to application/json. Setting Content-Length may also be required if it is not automatically.

I've tried playing around with `perform_post` to try to get the JSON body included but to no avail (and with odd results). Things like the following don't seem to work:
```
client.send("perform_post", 
    "/1.1/direct_messages/welcome_messages/new.json",
    json: {"welcome_message": {"message_data": {"text": "Hi, how can I help you?"}}})
``` 
For some reason this yields `Twitter::Error::Unauthorized: Could not authenticate you.`

FWIW, I am able to successfully create a new welcome message using Postman and the same tokens where the HTTP request looks as follows:
```
POST /1.1/direct_messages/welcome_messages/new.json HTTP/1.1
Host: api.twitter.com
Content-Type: application/json
Authorization: OAuth oauth_consumer_key="XXX",oauth_token="YYY",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1499253795",oauth_nonce="uxEkmmUQTP5",oauth_version="1.0",oauth_signature="ZZZ"
Cache-Control: no-cache
Postman-Token: cb1e9aa7-588a-04c8-e018-64ef0d0ba5f2

{
  "welcome_message" : {
    "message_data": {
      "text": "Hi, how can I help you?"
    }
  }
}
```

So I know I have the permissions to do this but the request from the `twitter` gem does not work. Basically what I'm asking is... How can I make the `twitter` gem send a request like the one above since I know this one works?

### LINKED ISSUE #869: Send images via DM
Is there a way to send images via DM? I know on the twitter API there is but can't seem to find if the gem supports it.

I think it has to do with events attachment or something like that.

Anyone can shed some light on this? Thanks!

### PR DESCRIPTION
**Pull request by shmargum**
This adds basic support for sending authenticated JSON post requests.
Resolves #862
Also resolves #869 

Example usage:

```ruby
    Twitter::REST::Request.new(
      client, # Twitter::REST::Client instance
      :json_post, # <-- this is important
      '/1.1/the-endpoint.json',
      {
        some_key: "some value",
      }
    ).perform
```

### CODE REVIEW

**Comment by shmargum** [comment]
@sferik hoping you can have a look at this

**Comment by bobber205** [comment]
I can confirm this allows me to create welcome messages easily!

**Comment by clarkbab** [comment]
Any movement on getting this merged? I believe that the old DM endpoints will cease to work on June 19th. Not long!

**Comment by bobber205** [comment]
FWIW the pull request is missing a put equivalent (I added a PR for it) https://github.com/shmargum/twitter/pull/1

**Pull request closed without merging**
