### PR TITLE
Fix rubocop configuration

### PR DESCRIPTION
**Pull request by mvz**
Update RuboCop configuration for RuboCop 0.49.1 and fix some offenses.

### CODE REVIEW

**Comment by mvz** [comment]
There was an extra offense on master compared to 6-stable. I just now added a commit to fix that last one.

**Comment by mvz** [comment]
New offenses appeared due to RuboCop 0.50.0 😞

**Comment by sferik** [comment]
Thanks for opening this PR. I resolved these issues myself before noticing you had already done this.

**Comment by mvz** [comment]
No problem. I'm glad 6.2.0 was released :tada:!

**Pull request closed without merging**
