### PR TITLE
Rely on rate limit during cursor iterating

### PR DESCRIPTION
**Pull request by timsly**
Let's imaging we have 5k followers and we want to cache them in our DB.
Current implementation  will allow us to get only first portion of all followers.
If we follow [Rate Limit Example](https://github.com/sferik/twitter/blob/3fc61e1f4860688689df0104347330fb1c796a32/examples/RateLimiting.md) `retry` will start getting items from the beginning, so i will still get same followers, but not those from the end of the followers list.

This is the experimental fix, if you find it useful i will add specs.

### CODE REVIEW

**Comment by sferik** [comment]
You should be able to achieve the same result by doing this: https://github.com/sferik/twitter/blob/master/examples/RateLimiting.md.

**Comment by timsly** [comment]
@sferik it's not the same.

For example you have 1000 followers and want to index them.

If we go according to the RateLimiting example, than i will be able to get 20 * 15 items, than api raises exception, we wait some time and call `retry` which will start getting followers from the beginning. This means that we never get more than 20 * 15 followers.
My PR implement retry inside results iterator

Also, i [cleaned up this branch](https://github.com/timsly/twitter/tree/cursor-rate-limit) so I can create another PR without all this strange commits

**Comment by sferik** [comment]
> If we go according to the RateLimiting example, than i will be able to get 20 * 15 items, than api raises exception, we wait some time and call `retry` which will start getting followers from the beginning. This means that we never get more than 20 * 15 followers.

@timsly That’s not how it’s supposed to work. `Twitter::Cursor` objects are designed to cache the collection and maintain a pointer to their current position in the collection, such that retries should not request the same data twice. If that functionality is broken, please open an issue.

**Comment by subimage** [comment]
Moreover, why isn't followers/following getting friend_ids, then bulk loading using https://dev.twitter.com/rest/reference/get/users/lookup ? It makes the gem unnecessarily slow from what I can see.

Am I missing something?

**Pull request closed without merging**
