### PR TITLE
to_hash returns empty hash.  Allows libraries like RABL to gracefully handle nulls

### PR DESCRIPTION
**Pull request by geori**
After I recently upgraded the Twitter library, I kept getting "TypeError - Twitter::NullObject.to_hash() did not return a Hash." in our app. I tracked the bug down to our RABL views calling the to_hash() on almost every property returned by Twitter::Tweet. The change I made allows RABL to gracefully handle null objects.

### CODE REVIEW

**Comment by sferik** [comment]
@avdi Should this be covered by `define_implicit_conversions`?

**Comment by geori** [comment]
I didn't think of that.  It would be much cleaner to update the define_implicit_conversions method in naught.

**Comment by sferik** [comment]
I’ve opened https://github.com/avdi/naught/pull/68. Let’s see what @avdi has to say about that.

**Comment by avdi** [comment]
Just to reiterate my response over there: very yes!

**Comment by sferik** [comment]
This has been [fixed in Naught](https://github.com/avdi/naught/pull/68).

**Pull request closed without merging**
