### PR TITLE
Video entities support

### PR DESCRIPTION
**Pull request by stve**
This PR add support for video entities that were [recently announced by Twitter](https://twittercommunity.com/t/twitter-video-support-in-rest-and-streaming-api/31258).  The API changes aren't currently available yet so this work is based off the example in their announcement. :clapper: 

While it's basically an overloaded photo object, I opted not to subclass `Twitter::Media::Photo` as it seems likely they'd diverge at some point. I opted to create a shared example for the properties that are shared by both objects. I noticed that the test suite didn't include any shared examples so this may not be preferred. If that's the case, I'm happy to change that back.

### CODE REVIEW

**Comment by sferik** [comment]
Awesome! You beat me to implementing this.

One addition step when adding or removing classes is running `bundle exec rake erd` to generate a new entity-relationship diagram. I’ll take care of it after merging.

**Comment by stve** [comment]
> One addition step when adding or removing classes is running bundle exec rake erd to generate a new entity-relationship diagram.

noted, thanks for merging

**Comment by sferik** [comment]
I’ve also been thinking about defining some of the value objects as structures, instead of with classes.

Arguably, classes like `Twitter::Variant` don’t belong in the ancestry hierarchy. I completely understand why you made it inherit from `Twitter::Base` (so you could define attributes via the `uri_attr_reader` class method), however, I think it’s probably a better design to define methods like `uri_attr_reader` in a module (i.e. composition over inheritance). I’m not necessarily proposing that we eliminate the `Twitter::Base` class or get rid of all inheritance but it feels like we’re using inheritance as a crutch in certain cases. I would even go as far as saying that `Base` classes are a code smell, in general. If you look at [Code Climate, sorting by complexity](https://codeclimate.com/github/sferik/twitter/code?sort=complexity&sort_direction=desc), `Twitter::Base` is our most complex class with a complexity rating of 150.

So, before we release [v6](https://github.com/sferik/twitter/milestones/v6), I’d like to make an attempt to refactor most of the behavior out of the `Twitter::Base` class into different modules and then reconsidering whether each class should inherit from `Twitter::Base` or simply be structures that mix-in one or more of those modules. On first pass, I think these are all candidates to be removed from the ancestry hierarchy:

* `Twitter::Entity`
* `Twitter::Geo`
* `Twitter::Language`
* `Twitter::MetaData`
* `Twitter::RateLimit`
* `Twitter::Size`
* `Twitter::Streaming::StallWarning`
* `Twitter::Variant`

By the way, when I say “structure” I’m not necessarily talking about the standard library `Struct` (or `OpenStruct`). Those are both candidates for what I’m talking about but I’d also look into using something like [`Values`](https://github.com/tcrayford/values), [`Virtus`](https://github.com/solnic/virtus), or possibly defining our own custom `Twitter::Struct`.

As always, I’m generally interested in your input on questions like this.

**Comment by stve** [comment]
> I’ve also been thinking about defining some of the value objects as structures

I completely agree. These objects can and should be lightweight.  There's also added complexity through inheritance with classes like `Twitter::Identity` which layer on `Twitter::Base` while adding minimal additional capability. This is definitely ripe for a refactor. It seems like it shouldn't be too difficult to decompose `Twitter::Base` into modules (where appropriate). I wasn't familiar with Values or Virtus, but both look like decent libraries to either use or mimic.

Note: presumably you generated that list off of master, I've added a [lot more](https://github.com/sferik/twitter/tree/streaming-updates/lib/twitter/streaming) of these small classes as part of #631

**Comment by sferik** [comment]
> Note: presumably you generated that list off of master, I've added a [lot more](https://github.com/sferik/twitter/tree/streaming-updates/lib/twitter/streaming) of these small classes as part of #631 

That’s correct. If there are even more small classes that can be converted to structures, I think that strengthens the case for making this refactoring. After thinking about it some more, I’m leaning toward creating a custom `ValueObject` class that I might even extract into a separate gem, since the other standard/third-party libraries aren’t exactly what I had in mind and I think it might be generally useful.

**Comment by sferik** [comment]
Just to capture what’s in my head, my requirements for `ValueObject` are…

- [ ] Can be initialized with a hash/kwargs (like `OpenStruct` or `Virtus`, but not `Struct` or `Values`)
- [ ] Immutable, possibly via [Adamantium](https://github.com/dkubb/adamantium) (like `Values` but not `Struct`, `OpenStruct`, or `Virtus`)
- [ ] [Value semantics](http://martinfowler.com/bliki/ValueObject.html), possibly via [Equalizer](https://github.com/dkubb/equalizer) (none of the above)

I think that’s it, but none of the existing libraries I know of meet these three requirements.

@stve Is there anything else you’d want in a value object?

**Comment by stve** [comment]
I can definitely see a library like the one you've described being useful outside of the Twitter gem. What you've laid out above makes perfect sense to me. I'm sure if we start there, we'll eventually discover a few more features we'd want along the way. Do you want to build this as `Twitter::ValueOjbect` for now and extract later?

**Comment by sferik** [comment]
LOL. I just checked to see if the `value_object` gem name was available and I think I found exactly what I was looking for: https://github.com/hdgarrood/value_object.

**Comment by stve** [comment]
Nice find! This looks to do nearly all of what you specified. The only red flag I saw was the dependency on ActiveSupport. Presumably there's a way to build some of that without requiring AS.

**Comment by sferik** [comment]
@stve Oh, dear. :scream: I did not notice that. Maybe they will accept a pull request to drop the `activesupport` dependency, vendoring the necessary ActiveSupport methods.

**Comment by sferik** [comment]
@stve I’ve taken a closer look at [Values](https://github.com/tcrayford/values) and it actually appears to meet all my requirements above without any dependencies.

**Pull request merged**
